# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configure VM Ram usage
  config.vm.provider "libvirt" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.box = "generic/ubuntu2204"
end
