# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configure VM Ram usage
  config.vm.provider "libvirt" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.box = "generic/ubuntu2204"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8096, host: 8096
  config.vm.provision "shell", path: "config.sh"
end