###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: a_very_important_secret
default_redirection_url: https://auth.home-server-flme.duckdns.org

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
  file_path: /config/authelia.log

totp:
  issuer: home-server-flme.duckdns.org

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: auth.home-server-flme.duckdns.org
      policy: bypass
    - domain: seafile.home-server-flme.duckdns.org
      policy: one_factor
    - domain: flame.home-server-flme.duckdns.org
      policy: one_factor
    - domain: home-server-flme.duckdns.org
      policy: one_factor

session:
  secret: unsecure_session_secret
  name: authelia_session
  domain: home-server-flme.duckdns.org  # Should match whatever your root protected domain is
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt

identity_providers:
  oidc:
    hmac_secret: this_is_a_secret_abc123abc123abc
    issuer_certificate_chain: |
      -----BEGIN CERTIFICATE-----
      MIIDETCCAfmgAwIBAgIQJeJ/i1e7dexZCIUON0hjCzANBgkqhkiG9w0BAQsFADAp
      MREwDwYDVQQKEwhBdXRoZWxpYTEUMBIGA1UEAxMLdGVuZWtldi5jb20wHhcNMjQw
      MjIyMDkzNjQ4WhcNMjUwMjIxMDkzNjQ4WjApMREwDwYDVQQKEwhBdXRoZWxpYTEU
      MBIGA1UEAxMLdGVuZWtldi5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      AoIBAQCx3bm68zxzKqsJgVuiCbhD2Rr6/DEn1Jf4vWZzd05WOUzBiPIVmSrVrot/
      hIG2tTmHG7KBTxAy6ZS8bJvknNX2lilaH19uqnE7VYEGprEHuM8EmQSRqKBtvJCA
      W2YgC6cYUZNwlbvk5HlVlEnAxz4GgS7HB312i0qSPGnd/sUV0sIsLAfnQxGDJqgI
      aRvDie25Nt4oUqGKlRXbpapCiR3zOusH6MotxMZCis9RvBCK9Zcl9UW7+hPkwxkz
      sl8SHlU6Aot7/kP+PbsXF1hy2wQ6khx2SKMq0cnNCLCucHyukEmmQqNCT5+X2ouu
      Lhs13F56A3FQPBGdz4NaDBH8sDYzAgMBAAGjNTAzMA4GA1UdDwEB/wQEAwIFoDAT
      BgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUA
      A4IBAQBjUHFzY842jiEhPiEDxrPUMRwum/fVaRovUoemrgnsKBrAOfcec8EITEY8
      wfpCVfNdMhFvOaKkk18vgt8Ob6s4HvOLZhDyeVeq8yowazyjcxCvytT5VzG5I4Kt
      X3UCZeEpH6YMEloGydpO5sEfMz37H1EanNT0BBhXN/wtGlRY3Ez93S/UBsDfEsI0
      NgBPTR6raSSDs60xSksazi//QWS4iYHAivZqa7Buk7OsvCVAP4Qv7iGXqy2jG3ec
      0CQahqW0WeAl1XzlZjuyL7mvLs7neSqR8mdCIexIlzC/yWdjdb0ldm1uZ/RoIS9T
      27NI7w0SOQ4bg88vYt5osIs5OY7t
      -----END CERTIFICATE-----
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEpAIBAAKCAQEAsd25uvM8cyqrCYFbogm4Q9ka+vwxJ9SX+L1mc3dOVjlMwYjy
      FZkq1a6Lf4SBtrU5hxuygU8QMumUvGyb5JzV9pYpWh9fbqpxO1WBBqaxB7jPBJkE
      kaigbbyQgFtmIAunGFGTcJW75OR5VZRJwMc+BoEuxwd9dotKkjxp3f7FFdLCLCwH
      50MRgyaoCGkbw4ntuTbeKFKhipUV26WqQokd8zrrB+jKLcTGQorPUbwQivWXJfVF
      u/oT5MMZM7JfEh5VOgKLe/5D/j27FxdYctsEOpIcdkijKtHJzQiwrnB8rpBJpkKj
      Qk+fl9qLri4bNdxeegNxUDwRnc+DWgwR/LA2MwIDAQABAoIBAQCVlAt/ptJtX7Ka
      ucifymDF3iyMac3E20o6ir0/2VNtu55LG6nKdBbLwI/b20lip6ELeEVz7VOIHVtR
      4lxvs11UlA+OlNeir3+uEEgDmedCwS6HhU+MVy0jW/KBn1uRE3ugPeoqQiHTajiH
      ub8Uefo1aio2gpwGNzmtJVU6teh0YnO4M0n6oO7X+nzXMXNR/M03mBTvF8sWCEMx
      CPKQNs1KhSUxKhnHaBsIWT0xlGvdutmjt7KLv6/hLkHcOV3kRTLGYe2FkNOwy5jW
      p2587fPcYrg6cKOLPz2iCmUpziPs59hvD0EUzUj+cvrnxcdDUjm1gcHWilRVCXLY
      y6Ro5VORAoGBAMYf/BFx+dayFi4u+9VvdsBP+3Efkd5Xq/nuUmHTj5FfP01QKQEe
      muUlvNiJ11S1gLNhBpMpG5S9lQC22cXwmZBpnlvmrskIB2hcRCdzUvxe7fHuwaQ/
      StaiBk4evS3yorW2Y0C6Hi2JIGUy8I+amFjefhB9vDbwAW1DKGcZs2MtAoGBAOXS
      wx9HL4b4cnO6ku7uqD7rqiiGhlG+L9OxSzPhBQ/A8ZM6ZTlDn7NGPGdXi0QRjJmu
      IQKUkW4QpGy8Jo7Uh1i1zPKijmA+9taPiHfLWStJr5u9PxVPHq06aWdYO+p0anuX
      6vpbA9VZOPNFt+8h+IAC+Z/95DexE3j85ONgK1rfAoGBAMM5BwclmLouFt8BGtLw
      F0JeTXPlWLWPC/2lEPYmIeRrxxNmdlENGDHNIqz3/f8RLbUTWQguzGee+zCN/D4n
      2xlKiWkjAH1EdRAnQlzhLRdSbwIichpm51ZgpvfZIC4jVKLbCifgfRX/dbViIVpP
      Sejfq7aSPqCfk7hXIXud/n4tAoGAHHNP5mJYltvQx1TUdbGjsE5aPTQSErJ5lzo+
      dgioKMAY58H13/XoIjhSp/RlcCLABhJRUdF0g2yZ/j/4gfv7WVcALRVEjNOemQch
      vLq2qi4wCBaQZaHqyUUO4VVB7Y9F01EGLMHxooquCyeZUoghDC/SGSVECETqhTLB
      Xwh7tX8CgYAZRMKCgkiSnMeGzc+k0+FtZ+xSX44uxsGW4gPxIVEI+W7zIsYMsONC
      zwU74slDfMW93rocXdA/YZU4Q1vgGub6wrIJNVyp0OsLTdoi93vqL8hBf9UKN47T
      fXoh82JEL1OSYGQZorYEUo+dQZ7PV4Qmg4Mysid/5Vt2WhWC+R2z/A==
      -----END RSA PRIVATE KEY-----
    access_token_lifespan: 1h
    authorize_code_lifespan: 1m
    id_token_lifespan: 1h
    refresh_token_lifespan: 90m
    enable_client_debug_messages: false
    enforce_pkce: public_clients_only
    cors:
      endpoints:
        - authorization
        - token
        - revocation
        - introspection
      allowed_origins:
        - https://home-server-flme.duckdns.org
      allowed_origins_from_client_redirect_uris: false
    clients:
    - id: seafile
      description: Seafile
      secret: '$pbkdf2-sha512$310000$c8p78n7pUMln0jzvd4aK4Q$JNRBzwAo0ek5qKn50cFzzvE9RXV88h1wJn5KGiHrD0YKtZaR/nCb2CJPOsKaPK0hjf.9yHxzQGZziziccp6Yng'  # The digest of 'insecure_secret'.
      public: false
      authorization_policy: one_factor
      redirect_uris:
        - https://seafile.home-server-flme.duckdns.org/oauth/callback/
      scopes:
        - openid
        - profile
        - email
      userinfo_signing_algorithm: none