---
- hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        pkg:
          - docker
        state: latest
        update_cache: true
    - name: Install FileBrowser
      ansible.builtin.shell: |
      docker run \
        -v /path/to/root:/srv \
        -v /path/to/filebrowser.db:/database/filebrowser.db \
        -v /path/to/settings.json:/config/settings.json \
        -e PUID=$(id -u) \
        -e PGID=$(id -g) \
        -p 8080:80 \
        filebrowser/filebrowser:s6